name: easy_input
description: A simple Python-style package for working with stdin and files.
version: 0.1.0
homepage: https://github.com/avdosev
repository: https://github.com/avdosev/easy_input_dart

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
